[package]
name = "watcher"
version = "1.0.0"
authors = [ "Blake Nedved <blakeanedved@gmail.com>" ]
description = "A simple application for watching a file and running a command whenever it changes"
edition = "2021"

[dependencies]
notify = "4"
clap = { version = "3", features = ["derive"] }
